#!/bin/sh
NC='\033[0m'
LP='\033[1;35m'

echo -e "#################################################################"
echo -e "############################ ${LP}MAPS${NC} ################################"
echo -e "#################################################################"

./gradlew integrate --stacktrace -Psource=Huayu28_x_P76.map.Hu_Zhang_2018
./gradlew integrate --stacktrace -Psource=ICGS44_x_ICGS76.map.Gautami_Pandey_2012
./gradlew integrate --stacktrace -Psource=ICGS76_x_CSMG84.map.Gautami_Pandey_2012
./gradlew integrate --stacktrace -Psource=mixed.map.Gautami_Pandey_2012
./gradlew integrate --stacktrace -Psource=mixed.map.Sujay_Gowda_2012
./gradlew integrate --stacktrace -Psource=TAG24_x_GPBD4.map.Kolekar_Sujay_2016
./gradlew integrate --stacktrace -Psource=TAG24_x_ICGV86031.map.Ravi_Vadez_2011
./gradlew integrate --stacktrace -Psource=TG26_x_GPBD4.map.Sarvamanga_Gowdaa_2011
./gradlew integrate --stacktrace -Psource=TG26_x_GPBD4.map.Sujay_Gowda_2012
./gradlew integrate --stacktrace -Psource=Tifrunner_x_GT-C20.map.Agarwal_Clevenger_2018
./gradlew integrate --stacktrace -Psource=Tifrunner_x_GT-C20.map.Qin_Feng_2012
./gradlew integrate --stacktrace -Psource=Tifrunner_x_GT-C20.map.Wang_Penmetsa_2012
./gradlew integrate --stacktrace -Psource=VG9514_x_TAG24.map.Mondal_Hadapad_2014
