#!/bin/sh
NC='\033[0m'
LP='\033[1;35m'
echo -e "#################################################################"
echo -e "############################ ${LP}GENOMES${NC} ############################"
echo -e "#################################################################"

./gradlew integrate --stacktrace -Psource=V14167.gnm1.SWBf
./gradlew integrate --stacktrace -Psource=Tifrunner.gnm1.KYV3
./gradlew integrate --stacktrace -Psource=Tifrunner.gnm2.J5K5
./gradlew integrate --stacktrace -Psource=K30076.gnm1.bXJ8
