#!/bin/sh
NC='\033[0m'
LP='\033[1;35m'

echo -e "#################################################################"
echo -e "############################ ${LP}SYNTENY${NC} ############################"
echo -e "#################################################################"

./gradlew integrate --stacktrace -Psource=V14167.gnm1.syn.qmkW
./gradlew integrate --stacktrace -Psource=K30076.gnm1.syn.S8s4
