#!/bin/sh
NC='\033[0m'
LP='\033[1;35m'
echo -e "#################################################################"
echo -e "########################### ${LP}ANNOTATION${NC} ##########################"
echo -e "#################################################################"

./gradlew integrate --stacktrace -Psource=V14167.gnm1.ann1.cxSM
./gradlew integrate --stacktrace -Psource=Tifrunner.gnm1.ann1.CCJH
./gradlew integrate --stacktrace -Psource=Tifrunner.gnm2.ann1.4K0L
./gradlew integrate --stacktrace -Psource=K30076.gnm1.ann1.J37m

